Repository avinashkranjan/Pentesting-and-Hacking-Scripts, pull requests merged in 2021-03, with the labels that each got.

#69 Update README.md
  README.md
Labels: GSSOC21, Level0

#76 Python3 compatibility issues with easyscope.py
  easyscope/README.md
  easyscope/easyscope.py
  easyscope/snapshot/output.png
  easyscope/snapshot/usage.JPG
Labels: Approved, GSSOC21, Level2, enhancement

#74 Added automated contributor list !!
  README.md
Labels: Approved, GSSOC21, Level2, enhancement

#70 65 add hash cracker automation
  Hash-Cracker/README.md
  Hash-Cracker/hash-checker.py
  README.md
Labels: Approved, GSSOC21, Level2, enhancement

#91 Updated README.md
  Discovering-Subdomains/README.md
Labels: Approved, GSSOC21, Level0

#85 Updated DoS attack repo
  ddos-attack/Readme.md
  ddos-attack/ddos.png
  dos-attack/Readme.md
  dos-attack/dos.png
  dos-attack/dos.py
Labels: Approved, GSSOC21, Level2

#84 Updated Keylogger
  Keylogger/README.md
  Keylogger/keylogger.py
  Keylogger/requirements.txt
Labels: Approved, GSSOC21, Level3, enhancement

#73 Stock market
  README.md
  Stock-Market-Data-Scraper/Readme.md
  Stock-Market-Data-Scraper/stock_market.py
Labels: Approved, GSSOC21, Level3, enhancement

#94 403 Bypass script
  403Bypass/403bypasser.py
  403Bypass/README.md
  403Bypass/requirements.txt
  SCRIPTS.md
Labels: GSSOC21, Level3, enhancement, under review

#105 Added requirments.txt for phone-numbers-tracker
  Phone-Number-Tracker/requirments.txt
Labels: GSSOC21, Level0

#106 Added requirments.txt file in Geolocation
  Geolocation/requirments.txt
Labels: GSSOC21, Level0

#107 Made changes in Discovering-Subdomains
  Discovering-Subdomains/README.md
  Discovering-Subdomains/program.py
  Discovering-Subdomains/subdomains.txt
Labels: GSSOC21, Level1

#96 Added Python-Nmap repository
  Python-Nmap/README.md
  Python-Nmap/requirements.txt
  Python-Nmap/sample.png
  Python-Nmap/scanner.py
Labels: GSSOC21, Level3, enhancement, under review

#104 Corrected issues with Who-Is/ and updated README.md
  Who-Is/whois.py
Labels: GSSOC21, Level2, under review

#109 syntax changed from python2 to python3 in all files of SniffAir direc…
  SniffAir/SniffAir.py
  SniffAir/lib/Connect2DB.py
  SniffAir/lib/Queries.py
  SniffAir/lib/Sniffer.py
Labels: GSSOC21, Level2

#87 Get wifi passwords stored on a remote system
  Wifi_passwords/README.md
  Wifi_passwords/wifi-passwords.py
Labels: GSSOC21, Level2, enhancement, under review

#112 Added threads support for directory busting script
  DirectoryBusting/README.md
  DirectoryBusting/directoryBuster.py
Labels: GSSOC21, Level3, enhancement, under review
