Repository avinashkranjan/Pentesting-and-Hacking-Scripts, pull requests merged in 2021-01, with the labels that each got.

#14 optimize code performance and fix anti-pattern
  Keylogger/keylogger.py
Labels: DWOC'21, Level-1

#22 Phone number Tracker #21
  Phone_number_Tracker/Readme.md
  Phone_number_Tracker/Tracker.py
  README.md
Labels: DWOC'21, Level-3

#23 Discovering Subdomains
  Discovering Subdomains/Output1.jpeg
  Discovering Subdomains/Output2.jpeg
  Discovering Subdomains/README.md
  Discovering Subdomains/program.py
  Discovering Subdomains/requirements.txt
  Discovering Subdomains/subdomain.txt
Labels: DWOC, Level-4
