Repository avinashkranjan/Pentesting-and-Hacking-Scripts, pull requests merged in 2021-05, with the labels that each got.

#131 Geolocation update
  Geolocation/Readme.md
  Geolocation/geolocation.py
  Geolocation/requirments.txt
Labels: GSSOC21, Level2, under review

#137 Adds script to generate wordlist from url(WFarm).
  SCRIPTS.md
  WFarm/README.md
  WFarm/example.png
  WFarm/wfarm.py
Labels: GSSOC21, Level3, under review

#139 Adds a tor utility script to setup and use tor
  SCRIPTS.md
  TorIT/README.md
  TorIT/example.png
  TorIT/torit.sh
Labels: GSSOC21, Level2, under review

#138 Adds a git utility script for easier usage (Noogit)
  Noogit/README.md
  Noogit/example.png
  Noogit/noogit.py
  SCRIPTS.md
Labels: GSSOC21, Level2, under review

#142 Adds thread support to WFarm
  WFarm/README.md
  WFarm/wfarm.py
Labels: GSSOC21, Level2, under review

#143 Update README.md
  README.md
Labels: GSSOC21, Level0

#141 Made Logos
  Logo pentesting.jpg
  logo 2 pentesting.png
Labels: GSSOC21, Level1, under review
