Repository avinashkranjan/Pentesting-and-Hacking-Scripts, pull requests merged in 2023-06, with the labels that each got.

#208 JS Phishing Detection
  Phishing Scripts/Readme.md
  Phishing Scripts/phish_test.js
Labels: Level3, gssoc23

#226 ADD: CROSSFIRE BUFFER OVERFLOW DEMONSTRATOR PYTHON SCRIPT ✨
  Crossfire_POC/README.md
  Crossfire_POC/crossfire.py
Labels: Level3, gssoc23

#218 Cipher buster by hj
  SCRIPTS.md
  cipher_buster/cipher_buster.py
  cipher_buster/readme.md
Labels: Level3, gssoc23

#222 Fixed #219 : PR Template
  .github/pull_request_template.yml
Labels: Level2, gssoc23

#225 Add text encryption script
  text_encryption/encryption_method.py
  text_encryption/readme.md
Labels: Level3, gssoc23

#229 Hide txt in img by hj
  Image_text_hider/img_text_hider.py
  Image_text_hider/readme.md
  Image_text_hider/requirements.txt
  SCRIPTS.md
Labels: Level3, gssoc23

#212 Added IP-Address Tracker GUI Script
  IP_Address/IP.py
  IP_Address/README.md
  IP_Address/Screenshots/Capture.PNG
Labels: Level2, gssoc23

#230 Password Cracker added
  Password_Cracker/Password_Cracker.py
  Password_Cracker/README.md
Labels: Level2, gssoc23

#232 Added header analysis scripts
  SCRIPTS.md
  http_headerAnalysis/Readme.md
  http_headerAnalysis/http.jpeg
  http_headerAnalysis/http.py
Labels: Level2, gssoc23

#234 Added Vulnerability Assessment and Scanning Script
  SCRIPTS.md
  Vulnerability Assessment and Scanning/README.md
  Vulnerability Assessment and Scanning/vulnerability_scanner.py
Labels: Level2, gssoc23

#236 Added Network Traffic Analyzer Script
  Network Traffic Analyzer/README.md
  Network Traffic Analyzer/network_traffic_analyzer.py
  SCRIPTS.md
Labels: Level3, gssoc23

#286 Update Tracker.py
  Image_text_hider/img_text_hider.py
  Phone-Number-Tracker/Tracker.py
Labels: gssoc23

#293 Update program.py
  Discovering-Subdomains/program.py
Labels: gssoc23, Approved

#295 [GSSoC'23] Morse Code Convertor Project Completed
  Morsecode_Convertor/Morsecode.py
  Morsecode_Convertor/README.md
  SCRIPTS.md
Labels: level1, level2, level3, gssoc23

#292 [ADDED]: STEWS Script
  STEWS/.github/workflows/link-check.yml
  STEWS/.github/workflows/lint.yml
  STEWS/README.md
  STEWS/WebSockets_AppSec_US_2021_Presentation.pdf
  STEWS/discovery/README.md
  STEWS/discovery/STEWS-discovery.sh
  STEWS/discovery/known-endpoints.txt
  STEWS/fingerprint/2021-IANA-subprotocols.txt
  STEWS/fingerprint/README.md
  STEWS/fingerprint/STEWS-fingerprint.py
  STEWS/fingerprint/fingerprint-example.jpg
  STEWS/fingerprint/requirements.txt
  STEWS/fingerprint/websocket-frame.jpg
  STEWS/mlc_config.json
  STEWS/paper.pdf
  STEWS/stews-image.jpg
  STEWS/vuln-detect/README.md
  STEWS/vuln-detect/STEWS-vuln-detect.py
  STEWS/vuln-detect/requirements.txt
Labels: Approved

#260 Added sqlmap script
  SCRIPTS.md
  Sqlmap/README.md
  Sqlmap/penetration_testing_script.py
  Sqlmap/requirements.txt
Labels: level3, gssoc23

#243 Added Web Application Scanner Script
  SCRIPTS.md
  Web Application Scanner/README.md
  Web Application Scanner/web_application_scanner.py
Labels: level3, gssoc23

#251 Cryptography : RSA algorithm
  Cryptography/RSA/README.md
  Cryptography/RSA/example.py
  Cryptography/RSA/rsa.py
  SCRIPTS.md
Labels: level2, gssoc23

#290 [Enhanced]: NightCall Script
  NightCall/nightcall.py
Labels: level2, gssoc23

#261 ADD: WEB APPLICATION VULNERABILITY SCANNER SCRIPT 👾
  SCRIPTS.md
  VulnScanner/README.md
  VulnScanner/script.rb
Labels: level3, gssoc23

#255 [Enhanced] : Domino Effect
  Domino-Effect/dominoeffect.py
Labels: level2, gssoc23

#262 Phone_number_tracker is updated with optimize code
  Phone-Number-Tracker/Tracker.py
Labels: level2, gssoc23

#298 [ADDED]: SocialBox-Termux
  SocialBox-Termux/.idea/.gitignore
  SocialBox-Termux/.idea/SocialBox-Termux.iml
  SocialBox-Termux/.idea/misc.xml
  SocialBox-Termux/.idea/modules.xml
  SocialBox-Termux/.idea/vcs.xml
  SocialBox-Termux/.whitesource
  SocialBox-Termux/README.md
  SocialBox-Termux/Screenshots/sb.png
  SocialBox-Termux/SocialBox.sh
  SocialBox-Termux/instainsane/LICENSE
  SocialBox-Termux/instainsane/README.md
  SocialBox-Termux/instainsane/instainsane.sh
  SocialBox-Termux/instainsane/install.sh
  SocialBox-Termux/instainsane/multitor/multitor1
  SocialBox-Termux/instainsane/multitor/multitor2
  SocialBox-Termux/instainsane/multitor/multitor3
  SocialBox-Termux/instainsane/multitor/multitor4
  SocialBox-Termux/instainsane/multitor/multitor5
  SocialBox-Termux/instainsane/passwords.lst
  SocialBox-Termux/install-sb.sh
  SocialBox-Termux/tweetshell/LICENSE
  SocialBox-Termux/tweetshell/README.md
  SocialBox-Termux/tweetshell/install.sh
  SocialBox-Termux/tweetshell/passwords.lst
  SocialBox-Termux/tweetshell/tweetshell.sh
Labels: level3, gssoc23

#310 Create Automatic_MAC_Address_changer.py
  Automatic_MAC_Address_changer.py
Labels: level2, gssoc23

#300 IP_address script is optimized
  IP_Address/IP.py
Labels: level2, gssoc23

#301 Geolocation script is optimize
  Geolocation/geolocation.py
Labels: level2, gssoc23

#302 Metaspolit script is added
  Metasploit script/Readme.md
  Metasploit script/script.py
  SCRIPTS.md
Labels: level2, gssoc23

#305 9Types_Hash_Cracker Added
  9Types_Hash_Cracker/9types_Hash_Cracker.py
  9Types_Hash_Cracker/README.md
Labels: level3, gssoc23

#307 FTP Password Cracker Added
  9Types_Hash_Cracker/README.md
  FTP_Password_Cracker/FTP.py
  FTP_Password_Cracker/README.md
Labels: level2, gssoc23

#308 [GSSoC'23] Telegram Automation Project Completed
  SCRIPTS.md
  Telegram_Automation/Automate_Telegram.py
  Telegram_Automation/README.md
  Telegram_Automation/Read-Me.txt
  Telegram_Automation/requirements.txt
Labels: level2, gssoc23

#322 Added Stenography Python Script
  Stenography/.gitignore
  Stenography/LICENSE
  Stenography/Pipfile
  Stenography/Pipfile.lock
  Stenography/README.md
  Stenography/SNOW.EXE
  Stenography/data.db
  Stenography/images/dots.png
  Stenography/images/home_screeen.png
  Stenography/images/img.png
  Stenography/images/l2.ico
  Stenography/images/l2.xbm
  Stenography/images/noshow.png
  Stenography/images/show.png
  Stenography/main.py
  Stenography/steno/__init__.py
  Stenography/steno/audio.py
  Stenography/steno/database.py
  Stenography/steno/hover.py
  Stenography/steno/image.py
  Stenography/steno/text.py
Labels: level2, gssoc23

#323 Update web_application_scanner.py
  Web Application Scanner/web_application_scanner.py
Labels: level2, gssoc23

#325 Added FTP_Cracker.py
  FTP_Cracker/FTP_Cracker.py
  FTP_Cracker/README.md
  SCRIPTS.md
Labels: level2, gssoc23

#326 added WebTech.py
  SCRIPTS.md
  WebTech/README.md
  WebTech/WebTech.py
Labels: level3, gssoc23
