Repository avinashkranjan/Pentesting-and-Hacking-Scripts, pull requests merged in 2023-07, with the labels that each got.

#328 feat: add codeql workflow
  .github/workflows/codeql.yml
Labels: level2, gssoc23

#329 [ADDED]: PhoneSploit Script
  PhoneSploit/.gitignore
  PhoneSploit/README.md
  PhoneSploit/_config.yml
  PhoneSploit/modules/banner.py
  PhoneSploit/modules/color.py
  PhoneSploit/modules/nmap/__init__.py
  PhoneSploit/modules/nmap/nmap.py
  PhoneSploit/modules/nmap/test_nmap.py
  PhoneSploit/modules/release.py
  PhoneSploit/phonesploitpro.py
  SCRIPTS.md
Labels: level3, gssoc23

#327 DOOM port Scanner is added
  DOOM_port_Scanner/DOOM.py
  DOOM_port_Scanner/Readme.md
Labels: level3, gssoc23

#334 Ghost track
  DDoS-Ripper/DRipper.py
  GhostTracker/GhostTR.py
  GhostTracker/Readme.md
Labels: level2, gssoc23

#335 [ADDED]: Cloakify Script
  Cloakify/README.md
  Cloakify/ciphers/amphibians
  Cloakify/ciphers/belgianBeers
  Cloakify/ciphers/desserts
  Cloakify/ciphers/dessertsArabic
  Cloakify/ciphers/dessertsChinese
  Cloakify/ciphers/dessertsHindi
  Cloakify/ciphers/dessertsPersian
  Cloakify/ciphers/dessertsRussian
  Cloakify/ciphers/dessertsSwedishChef
  Cloakify/ciphers/dessertsThai
  Cloakify/ciphers/emoji
  Cloakify/ciphers/evadeAV
  Cloakify/ciphers/geoCoordsWorldCapitals
  Cloakify/ciphers/geocache
  Cloakify/ciphers/hashesMD5
  Cloakify/ciphers/ipAddressesTop100
  Cloakify/ciphers/pokemonGo
  Cloakify/ciphers/rickrollYoutube
  Cloakify/ciphers/skiResorts
  Cloakify/ciphers/starTrek
  Cloakify/ciphers/statusCodes
  Cloakify/ciphers/topWebsites
  Cloakify/ciphers/worldBeaches
  Cloakify/ciphers/worldFootballTeams
  Cloakify/cloakify.py
  Cloakify/cloakifyFactory.py
  Cloakify/decloakify.py
  Cloakify/listsUnrandomized/amphibians.txt
  Cloakify/listsUnrandomized/arabic.txt
  Cloakify/listsUnrandomized/belgianBeers.txt
  Cloakify/listsUnrandomized/chinese.txt
  Cloakify/listsUnrandomized/desserts.txt
  Cloakify/listsUnrandomized/emoji.txt
  Cloakify/listsUnrandomized/evadeAV.txt
  Cloakify/listsUnrandomized/geoCoordsWorldCapitals.txt
  Cloakify/listsUnrandomized/geocache.txt
  Cloakify/listsUnrandomized/hashes.txt
  Cloakify/listsUnrandomized/hindi.txt
  Cloakify/listsUnrandomized/ipAddresses.txt
  Cloakify/listsUnrandomized/persian.txt
  Cloakify/listsUnrandomized/pokemonGo.txt
  Cloakify/listsUnrandomized/russian.txt
  Cloakify/listsUnrandomized/skiResorts.txt
  Cloakify/listsUnrandomized/starTrek.txt
  Cloakify/listsUnrandomized/swedishChef.txt
  Cloakify/listsUnrandomized/thai.txt
  Cloakify/listsUnrandomized/topWebsites.txt
  Cloakify/listsUnrandomized/worldBeaches.txt
  Cloakify/listsUnrandomized/worldFootballTeams.txt
  Cloakify/noiseTools/prependEmoji.py
  Cloakify/noiseTools/prependID.py
  Cloakify/noiseTools/prependLatLonCoords.py
  Cloakify/noiseTools/prependTimestamps.py
  Cloakify/randomizeCipherExample.txt
  Cloakify/removeNoise.py
  SCRIPTS.md
Labels: level3, gssoc23

#349 [GSSoC'23] Controls System Apps Project Completed
  Open-Close-Apps_Automation/OpenCloseApps.py
  Open-Close-Apps_Automation/README.md
  Open-Close-Apps_Automation/requirements.txt
  SCRIPTS.md
Labels: level2, gssoc23

#351 feat: Create Website for Pentesting-and-Hacking-Scripts Project
  .gitignore
  Website/.eslintrc.cjs
  Website/.gitignore
  Website/Image/hacker.png
  Website/index.html
  Website/package-lock.json
  Website/package.json
  Website/postcss.config.js
  Website/public/vite.svg
  Website/server/app.js
  Website/server/jsonresponse.js
  Website/server/package-lock.json
  Website/server/package.json
  Website/server/test.js
  Website/src/App.css
  Website/src/App.jsx
  Website/src/Image/empty-folder.png
  Website/src/Image/h2.png
  Website/src/Image/hacker.png
  Website/src/Pages/Home.jsx
  Website/src/componets/Card.jsx
  Website/src/componets/Card.scss
  Website/src/componets/Footer.jsx
  Website/src/componets/HeroSec.jsx
  Website/src/componets/Navbar.jsx
  Website/src/componets/NewFolder.jsx
  Website/src/componets/Searchbar.jsx
  Website/src/index.css
  Website/src/main.jsx
  Website/tailwind.config.js
  Website/vercel.json
  Website/vite.config.js
  package-lock.json
  package.json
Labels: level3, gssoc23

#352 [GSSOC'23] Ipdrone Script added
  IPdrone/README.Md
  IPdrone/ipdrone.py
Labels: level2, gssoc23

#353 added dns_dump.py ✅
  DNS_Dump/README.md
  DNS_Dump/dns_dump.py
  SCRIPTS.md
Labels: level2, gssoc23

#371 steal_all_files
  stealing_all_files/LICENSE.md
  stealing_all_files/README.md
  stealing_all_files/autorun.inf
  stealing_all_files/help.txt
  stealing_all_files/img/logo.png
  stealing_all_files/requirements.txt
  stealing_all_files/script.py
  stealing_all_files/test_script.py
Labels: level2, gssoc23

#354 added FileServer.py ✅
  File_Server/FileServer.py
  File_Server/README.m
  SCRIPTS.md
Labels: level2, gssoc23

#356 Added DOS Attack Python Script
  DOS/dos.py
Labels: level2, gssoc23

#362 [GSSoC'23] Wayback Machine Script Completed
  SCRIPTS.md
  Wayback_Machine/README.md
  Wayback_Machine/waybackmachine.py
Labels: level3, gssoc23

#364 [GSSoC'23] Github Automation Project Completed
  Automate_Github/Github_Automation.py
  Automate_Github/README.md
  SCRIPTS.md
Labels: level2, gssoc23

#368 Flooder sniffer
  Flooder_Sniffer_Spoofer/Readme.md
  Flooder_Sniffer_Spoofer/sniifer.spoofer.py
  SCRIPTS.md
Labels: level3, gssoc23

#369 Network analysis
  Network_analysis/Readme.md
  Network_analysis/network_analysis.py
  SCRIPTS.md
Labels: level2, gssoc23

#382 powershell bypass and py1 convert it into base64
  powershell/Readme.md
  powershell/example.ps1
  powershell/powershell_cmd_stager.py
Labels: level2, gssoc23

#384 feat: workflow to prevent multiple issues 🔐
  .github/workflows/prevent_multiple_issues.yml
Labels: level3, gssoc23

#390 Email_Spoof added
  Email_Spoof/README.md
  Email_Spoof/requirements.txt
  Email_Spoof/spoofy.py
Labels: level2, gssoc23

#393 Proxy_Script Added
  Proxy/Proxy_Script.py
  Proxy/README.md
  Proxy/requirements.txt
  Transmission_Control_Protocol_Client/README.md
  Transmission_Control_Protocol_Client/Transmission_Control_Protocol_Client.py
  Transmission_Control_Protocol_Client/requirements.txt
  Transmission_Control_Protocol_Server/README.md
  Transmission_Control_Protocol_Server/Transmission_Control_Protocol_Server.py
  Transmission_Control_Protocol_Server/requirements.txt
Labels: level2, gssoc23

#391 Transmission_Control_Protocol_Server Script Added
  Transmission_Control_Protocol_Server/README.md
Labels: level2, gssoc23

#394 added shellstorm.py
  SCRIPTS.md
  Shell_Storm/README.m
  Shell_Storm/shellstorm.py
Labels: level2, gssoc23

#396 added ENUM Forms Python Script
  ENUM_Forms/REAMDE.md
  ENUM_Forms/enum_forms.py
  SCRIPTS.md
Labels: level2, gssoc23

#397 Fixed mistakes in README
  README.md
Labels: level1, gssoc23

#402 [ADDED]: IP Location Finder
  IP_Location/README.md
  IP_Location/finder.py
  IP_Location/requirements.txt
  SCRIPTS.md
Labels: level2, gssoc23

#408 Phone_Locator
  Phone_Locator/README.md
  Phone_Locator/main.py
  Phone_Locator/requirements.txt
Labels: level3, gssoc23

#421 Enhanced Auto Comment on Issue or Pull Request
  .github/workflows/greetings.yml
Labels: level2, gssoc23

#423 Auto assign feature added
  .github/workflows/auto-assign.yml
Labels: level2, gssoc23

#419 Hacker env script
  SCRIPTS.md
  hackerEnv/Readme.md
  hackerEnv/hackerenv.py
Labels: level3, gssoc23

#418 Dot dot slash script
  SCRIPTS.md
  dotdotslash/Readme.md
  dotdotslash/dotdotslash.py
Labels: level3, gssoc23

#417 [ADDED]: DumpsterFire Tool
  Dumpster_Fire/Fire.py
  Dumpster_Fire/More_Info.md
  Dumpster_Fire/README.md
  Dumpster_Fire/requirements.txt
  SCRIPTS.md
Labels: level3, gssoc23

#416 Meta_Data_Info_Script
  Dirbrute/Dirbrute_Script.py
  Dirbrute/README.md
  Google_Info_Script/Google_Info_Script.py
  Google_Info_Script/README.md
  HTTP_Server/HTTP_Server.py
  HTTP_Server/README.md
  Jwt_Secret_Bruteforce/Jwt_Secret_Bruteforce.py
  Jwt_Secret_Bruteforce/README.md
  Meta_Data_Info_Script/Meta_Data_Info_Script.py
  Meta_Data_Info_Script/README.md
  SSH_Cracker/README.md
  SSH_Cracker/SSH_Cracker.py
Labels: level2, gssoc23

#424 [ADDED]: Ciphey Tool
  Ciphey tool/README.md
  Ciphey tool/ciphey.py
  Ciphey tool/dependencies.md
  Ciphey tool/requirements.txt
Labels: level2, gssoc23

#425 [ADDED]: Hoax Shell Tool
  Hoax_Shell/README.md
  Hoax_Shell/dependencies.md
  Hoax_Shell/hoax.py
  Hoax_Shell/requirements.txt
Labels: level2, gssoc23

#432 Create beautifulsoup.py
  Web scraping beautifulsoup/beautifulsoup.py
Labels: level2, gssoc23

#433 [GSSoC'23] Instagram Automation Project Completed
  Instagram-Automation/README.md
  Instagram-Automation/insta-auto.py
  SCRIPTS.md
Labels: level2, gssoc23

#436 Dirbrute_Script is added
  Dirbrute_Script/Dirbrute_Script.py
  Dirbrute_Script/README.md
Labels: level2, gssoc23

#438 Cross linked script
  CrossLinked/Readme.md
  CrossLinked/logger.py
  CrossLinked/search.py
  CrossLinked/utils.py
  SCRIPTS.md
Labels: level2, gssoc23

#439 EggShell python script
  EggShell/Readme.md
  EggShell/eggshell.py
  SCRIPTS.md
Labels: level2, gssoc23

#441 Update README
  encrypt_string/README
Labels: level1, gssoc23

#461 Create Script.py - Data visualization
  Data Visualization Script/Script.py
Labels: level2, gssoc23

#442 HTTP_Server script added
  HTTP_Server/HTTP_Server.py
  HTTP_Server/README.md
  SSH_Cracker/README.md
  SSH_Cracker/SSH_Cracker.py
Labels: level2, gssoc23

#446 docs: update dependabot workflow
  .github/dependabot.yml
Labels: level2, gssoc23

#454 [GSSoC'23] Skype Automation Completed
  SCRIPTS.md
  Skype-Automation/README.md
  Skype-Automation/skype.py
Labels: level2, gssoc23

#464 Jwt_Secret_Bruteforce_Script added
  Jwt_Secret_Bruteforce_Script/Jwt_Secret_Bruteforce_Script.py
  Jwt_Secret_Bruteforce_Script/README.md
Labels: level2, gssoc23

#463 Doom port optimization
  DOOM_port_Scanner/DOOM.py
  DOOM_port_Scanner/Readme.md
  Port-Scanner/Port_Scanner.py
Labels: level2, gssoc23
