Repository avinashkranjan/Pentesting-and-Hacking-Scripts, pull requests merged in 2023-08, with the labels that each got.

#474 Added Network Packet Sniffing Script
  Network Packet Sniffing/Network Pakcet Sniffing.py
  Network Packet Sniffing/README.md
Labels: level2, gssoc23

#479 Email automation script
  Automated_email/email_automation.py
  Automated_email/readme.md
Labels: level2, gssoc23

#480 [ADDED]: Evil URL Tool
  EvilURL/README.md
  EvilURL/evilurl.py
  EvilURL/requirements.txt
Labels: level2, gssoc23

#459 Create Email Automation Script.py
  Email script/Email Automation Script.py
Labels: level2, gssoc23

#472 docs: add workflow to assign PR to its author
  .github/ISSUE_TEMPLATE/script-addition.yml
  .github/workflows/author-assign-pr.yml
Labels: level2, gssoc23

#471 Sniffer_Id_Header_Decode_Script
  Content_Bruter_Script/Content_Bruter_Script.py
  Content_Bruter_Script/README.md
  Cred_Server_Script/Cred_Server_Script.py
  Cred_Server_Script/README.md
  Ddos_Attack_Script/DDOS_Attack_Script.py
  Ddos_Attack_Script/README.md
  SSH_Cracker_Script/README.md
  SSH_Cracker_Script/SSH_Cracker_Script.py
  Sandbox_Detect_Script/README.md
  Sandbox_Detect_Script/Sandbox_Detect_Script.py
  Sniffer_Id_Header_Decode_Script/README.md
  Sniffer_Id_Header_Decode_Script/Sniffer_Id_Header_Decode_Script.py
Labels: level2, gssoc23

#466 feat: added new feature i.e text decrypter
  EggShell/eggshell.py
  SCRIPTS.md
  text_decryption/README.md
  text_decryption/encrypt_decrypt.py
  text_decryption/requirements.txt
Labels: level2, gssoc23

#497 WebStor Script
  SCRIPTS.md
  WebStor/Readme.md
  WebStor/webstor.py
Labels: level2, gssoc23

#495 [ADDED]: Hash Buster
  Hash Buster/README.md
  Hash Buster/buster.py
  Hash Buster/requirements.txt
Labels: level2, gssoc23

#494 docs: add workflow to include labels after analyzing title of PR
  .github/labeler-config.yml
  .github/workflows/add-labels-pr.yml
Labels: level2, gssoc23

#487 CredPhish script
  CredPhish/Readme.md
  CredPhish/dns_server.py
  SCRIPTS.md
Labels: good first issue, level2, gssoc23

#485 RapidScan script
  RapidScan/Readme.md
  RapidScan/rapidscan.py
  RapidScan/setup.py
  SCRIPTS.md
Labels: level2, gssoc23

#481 feat: Added styles.yml File in GitHub Issue Templates List
  .github/ISSUE_TEMPLATE/styles.yml
Labels: level2, gssoc23

#492 feat: Added Multiple Workflows in GitHub workflows Sub-Folder
  .github/workflows/auto-comment-pr.yml
  .github/workflows/close_old_issues.yml
  .github/workflows/issue-close-greet.yml
  .github/workflows/issues.yml
  .github/workflows/linting.yml
  .github/workflows/lock.yml
  .github/workflows/pr-close-greet.yml
Labels: level3, gssoc23

#490 CCTV_Hack
  CCTV_Hack/Readme.md
  CCTV_Hack/cctv.py
  SCRIPTS.md
Labels: level2, gssoc23

#501 Lazy Bee script
  LazyBee/Readme.md
  LazyBee/lazybee.py
  SCRIPTS.md
Labels: level2, gssoc23

#502 Nero Phishing server
  Nero-Phishing-Server/Readme.md
  Nero-Phishing-Server/help.py
  Nero-Phishing-Server/httpd.py
  Nero-Phishing-Server/nero.py
  SCRIPTS.md
Labels: level2, gssoc23

#505 RPCScan script
  RPCScan/Readme.md
  RPCScan/scanner.py
  RPCScan/setup.py
  RPCScan/termux.py
  SCRIPTS.md
Labels: level2, gssoc23

#503 B11 script
  B11/Readme.md
  B11/main.py
  SCRIPTS.md
Labels: level2, gssoc23

#509 fix: Added admin social handles links
  README.md
Labels: documentation, level1, gssoc23

#507 feat: added dynamic contributors section
  README.md
Labels: enhancement, level2, gssoc23

#511 Payload script
  Payload/Readme.md
  Payload/payload.py
  SCRIPTS.md
Labels: level2, gssoc23

#513 Subchecker script
  SCRIPTS.md
  Subchecker/Readme.md
  Subchecker/subchecker.py
Labels: level2, gssoc23

#528 Crypto script
  Crypto/Readme.md
  Crypto/crypto.py
  SCRIPTS.md
Labels: level2, gssoc23

#520 [ADDED]: PyShell Tool
  PyShell/README.md
  PyShell/pyshell.py
  PyShell/requirements.txt
Labels: level2, gssoc23

#531 Email Nuker
  Email-nuker/Readme.md
  Email-nuker/bomber.py
  Email-nuker/emailbomber.py
  SCRIPTS.md
Labels: level2, gssoc23

#535 Added Insta hack
  InstaHack/README.md
  InstaHack/cred.txt
  InstaHack/insta.py
  InstaHack/install.sh
Labels: level2, gssoc23
